### ISSUE TITLE
Read me data on how to run parallel tests on cross browsers

### ISSUE THREAD

**Issue by praveenrp1610** [hdorgeval/playwright-fluent-ts-cucumber6-starter#2]
Hi @hdorgeval ,

Can you please help with the below data ?
1. Running the tests in parallel
2. Running simultaneously on different browsers

**Comment by hdorgeval** [comment]
Hi @praveenrp1610 : to run tests in parallel, you must add to the cucumber command-line the option `--parallel <NUMBER_OF_WORKERS>`.

Or you can also set the parallel execution directly after `npm test`:

```sh
npm test -- -- --parallel 3
```

**Comment by hdorgeval** [comment]
@praveenrp1610 : to run test on multiple browsers, you can use the updated version of this template. But be careful, that the last run will override the previous HTML report. If you want to run simultaneously all tests on all possible browsers, the provided template project needs further adaptation, because I assume that in the end, you would like to have only one HTML report for all tests and browsers.

**Comment by praveenrp1610** [comment]
Thanks @hdorgeval Makes sense
